controller_manager:
  ros__parameters:
    update_rate: 25
    
    bicycle_steering_controller:
      type: bicycle_steering_controller/BicycleSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
bicycle_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    rear_wheels_names: ['virtual_rear_wheel_joint']
    front_wheels_names: ['virtual_front_wheel_joint']
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    wheelbase: 0.26
    front_wheel_radius: 0.045
    rear_wheel_radius: 0.045

# joint_broad:
#   ros__parameters: